language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.5 DB=postgres
  - DJANGO=1.6 DB=postgres
  - DJANGO=1.7 DB=postgres
  - DJANGO=1.8 DB=postgres
  - DJANGO=1.9 DB=postgres
  - DJANGO=1.5 DB=mysql
  - DJANGO=1.6 DB=mysql
  - DJANGO=1.7 DB=mysql
  - DJANGO=1.8 DB=mysql
  - DJANGO=1.9 DB=mysql
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO=1.5 DB=postgres
    - python: "3.5"
      env: DJANGO=1.5 DB=mysql
    - python: "3.5"
      env: DJANGO=1.6 DB=postgres
    - python: "3.5"
      env: DJANGO=1.6 DB=mysql
    - python: "3.5"
      env: DJANGO=1.7 DB=postgres
    - python: "3.5"
      env: DJANGO=1.7 DB=mysql
before_script:
  - mysql -e 'create database django;'
  - psql -c 'create database django;' -U postgres
install:
  - if [[ $DB == mysql ]]; then pip install mysqlclient; fi
  - if [[ $DB == postgres ]]; then pip install psycopg2; fi
  - DJANGO_VER=$(./travis_django_version.py $DJANGO)
  - pip install $DJANGO_VER
  - pip install coveralls
  - pip install .
script:
  - django-admin.py --version
  - coverage run --source=m2m_history quicktest.py m2m_history
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - ramusus@gmail.com
    on_success: change
    on_failure: change
